port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: kydh
    server: www.sushiroll.co.id
    port: 443
    type: vless
    uuid: f2259b5d-0c6b-4a6d-89ff-70e18b9f41b6
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: klyro-sgvip.gachorr.web.id
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: klyro-sgvip.gachorr.web.id
    udp: true
  - name: kydh
    server: web.poe.garena.com
    port: 443
    type: vless
    uuid: 9cf9a9b0-2e2e-45bd-ac6f-5eaa44e30cfe
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: klyro-sgvip.gachorr.web.id
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: klyro-sgvip.gachorr.web.id
    udp: true
  - name: AKUN3
    server: quiz.int.vidio.com
    port: 443
    type: vless
    uuid: aae98731-898a-4cd3-8c7f-d09af2387d63
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: id2vless.ipservers.xyz
    udp: true

proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - kydh
      - kydh
      - AKUN3

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - kydh
      - kydh
      - AKUN3
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
